targetNamespace: ''
parameters: {}
environment: {}
packages:
  - name: aerolopa
    environment:
      AEROLOPA_FUNCTION_SECRET: '${AEROLOPA_FUNCTION_SECRET}'
    functions:
      - name: seatmap
        runtime: 'nodejs:24'
        main: main
        web: true
        webSecure: '${AEROLOPA_FUNCTION_SECRET}'
        limits:
          timeout: 60000
          memory: 512
